#!/bin/bash

#MYPATH=$(dirname $0)

cd /opt/mint-boxen && r10k puppetfile install
#sudo puppet apply $MYPATH/uboxen.pp
sudo puppet apply /etc/puppet/manifests/site.pp
etckeep "After uBoxen run"

exit 0
